### ISSUE TITLE
buttons out of fit in Nylas 0-4-14-53

### ISSUE THREAD

**Issue by rhoconlinux** [edipox/elementary-nylas#4]
Hello!
Very nice work, but since the latest updates of Nylas something is not fitting. Check out my screenshot:

![](http://i.imgur.com/qi2WRsh.png)

The buttons are out of the main bar, standing a bit over the sidebar and the email section. Probably a little bit of bottom-padding in the main button bar might solve this?

Cheers and keep it going! this is really good work.

**Comment by rhoconlinux** [comment]
This behavior persists in 0-4-16-x

**Comment by edipox** [comment]
Thank you @rhoconlinux I'll take a look

**Comment by edipox** [comment]
@rhoconlinux I couldn't reproduce the issue. Have you updated the theme? You have to manually reinstall or if you have git you can clone the repo in execute git pull origin master

**Comment by edipox** [comment]
With "manually reinstall" I mean remove the folders ~/.nylas/packages/ElementarySoftTheme and ~/.nylas/packages/ElementaryFullTheme, download the themes again and install using Nylas N1

**Comment by rhoconlinux** [comment]
Thank you! 
Yes, it is weard. I manually installed the theme by creating the packages folder and pasting the Elementary themes there, and its working now. 
Playing around to reproduce the issue i installed the theme using the "install theme" feature in nylas... and voilá, probably that is the source of this error. (?) jaja thank you for the help :)

**Comment by edipox** [comment]
No problem
